import type { NextPage } from 'next';
import Head from 'next/head';

const Home: NextPage = () => {
    return (
        <div>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
            </Head>

            <main>
                <p>
                    RobotX is a FRC team of aspiring, STEM passionate students. We're based in Khan
                    Lab School, in Mountain View, California where hands-on-learning and
                    passion-driven work are encouraged. We aim to inspire and expose others to the
                    exploration of science, mathematics, computer science, and technology; represent
                    our self-driven school in FRC competitions; and share our experiences and
                    knowledge with the rest of our community.
                </p>
            </main>
        </div>
    );
};

export default Home;
